Basic playbook setting prereqs on host
Akrog/rhoso-rhelai pull request #7
Opened 2024-12-16 15:30 UTC by jpodivin

2025-01-07 19:04 UTC, csibbitt requested changes
Nice work, thank you, @jpodivin!

I've spotted two potential problems and have a few other nit-picks I'd like to hear back about.

2025-01-07 19:04 UTC, csibbitt commented on nested-passthrough/ansible/setup_gpu/tasks/main.yaml
> +---
AFAICT, this file is unused? Is this so you can use setup_gpu as a stand-alone role? If so, why are you preferring to do `tasks_from` on each file (in setup_host.yml) rather than just including the top-level role and relying on this file to include your tasks?

Also noticed that this file leaves out iommu.yml, which is mentioned in setup_host.yml without an obvious reason (to me).

I feel like I might be missing something here, ansible plays tricks on me sometimes. :)

2025-01-08 09:16 UTC, jpodivin commented on nested-passthrough/ansible/setup_gpu/tasks/gpuinfo.yml
> +    gpu_pci_vendor_id: "{{ gpu_vendor_id }}"
Idea here is to make them available for followup plays. Otherwise we would have to find those values again. Actually I should make these cacheable so it works even for other executions.

2025-01-08 09:20 UTC, jpodivin commented on nested-passthrough/ansible/setup_gpu/tasks/iommu.yml
> +  failed_when: "'PASS' not in iommu_validation_result.stdout"
That's a good point. Flipping it.

2025-01-08 09:40 UTC, jpodivin commented on nested-passthrough/ansible/setup_gpu/tasks/grub.yml
> +      grub2-mkconfig -o {{ grub_config_path }}
On RHEL < 9 it was possible to rewrite `/boot/efi/EFI/$OS/grub.cfg` UEFI machines, that's still the way it's described in README from Gorka. In 9 it's not allowed anymore. And yes. since we are running all of this on top of RHEL>9, it's basically redundant.

But there was the possibility that the RHEL<9 way is somehow necessary for Gorkas own workflow, and I didn't want to mess with that.

So I've ended up with this compromise. If you want to follow the original README, you still can. If you want the configuration written somewhere else, that's also an option. If you don't care, there is no difference. The task just works with the same file twice.

If we all agree that it's just going to run on RHEL>9, we can get rid of this.

2025-01-08 09:49 UTC, jpodivin commented on nested-passthrough/ansible/setup_gpu/tasks/main.yaml
> +---
In practice it doesn't really matter. You could just call main, unless you have a good reason to just use some subset of tasks implemented in the role. In this case we really do want to call all of them.

But I do assume that both playbook and role will get more complex, as we support more hardware combos. At that point it may be necessary to work with conditionals. 

In our ansible collections those end up in playbook, while the main.yml remains as as sort *base* case. 
I'm trying to follow that pattern here, reasoning that it may make things easier in the future.

As for the iommu.yml, yeah I forgot about that one.

2025-01-08 10:08 UTC, jpodivin commented on nested-passthrough/ansible/setup_gpu/tasks/vfio.yml
> +      grubby --update-kernel ALL --args "rd.driver.pre=vfio_pci vfio_pci.ids={{ gpu_pci_id }} modules-load=vfio,vfio-pci,vfio_iommu_type1,vfio_pci_vfio_virqfd"
Good catch.

2025-01-08 14:32 UTC, csibbitt approved these changes
Thanks for the updates and explanations.

Final comments:

- I find a PR Description is helpful for a reviewer to know your intended scope and focus of the changes
- Unlike gerrit, where force-push is handled smoothly, a force-push in github makes it (IMO) harder to review changes, and a PITA for anyone who has pulled a local copy. I don't make rules, but if I did, banning force-push in GH would be one of them.

2025-01-14 16:09 UTC, Akrog requested changes
Please make the AMD vendor ID changes.  The rest, are just nits and are not required for merging the PR.

2025-01-14 16:09 UTC, Akrog commented on nested-passthrough/ansible/setup_host.yml
> +        tasks_from: drivers.yml
nit: maybe a better name would have included the word blacklist to make it more clear what it does.

2025-01-15 08:39 UTC, jpodivin commented on nested-passthrough/README.md
> +**Note:** Modifications to hypervisor PCI reservations, IOMMU etc can also be performed by the `ansible/setup_host.yml` ansible playbook.
Technically speaking there are several cases when the line goes over 80 chars already.
It's in the code and links, granted. But the 80 char limit is only really useful in constrained terminal widths.
If you open the file in environment like that it's going to look awful now matter what, as neither the links nor code blocks get any special treatment.

2025-01-15 10:09 UTC, Akrog approved these changes
LGTM

2025-01-15 10:09 UTC, merged